Brahim
BrahimKedjar/Univlabw3d pull request #2
Opened 2022-11-09 23:57 UTC by BrahimKedjar

2022-11-11 23:07 UTC, nminfo86 commented on database/migrations/2022_11_11_191013_modules.php
> +            $table->unsignedBigInteger('users_id')->nullable();
change this to user_id and not users_id

2022-11-11 23:09 UTC, nminfo86 commented on database/migrations/2022_11_11_192021_faculties.php
> +            $table->string('faculte')->nullable();
change this to faculty not faculte

2022-11-11 23:15 UTC, nminfo86 requested changes
Please see comments before merge to main branch

2022-11-12 21:09 UTC, BrahimKedjar commented on database/migrations/2022_11_11_192021_faculties.php
> +            $table->string('faculte')->nullable();
done

2022-11-12 21:10 UTC, BrahimKedjar commented on database/migrations/2022_11_11_191013_modules.php
> +            $table->unsignedBigInteger('users_id')->nullable();
done

2022-11-12 21:28 UTC, nminfo86 approved these changes
ya3ik saha

2022-11-12 21:29 UTC, merged